"use client";

import React from "react";
import styles from "../../DesignSystem.module.scss";
import { Badge } from "@/components/ui/Badge";
import Story from "../../Story";
import DocSection from "../../DocSection";
import { usePropControls } from "../../hooks/usePropControls";

export default function BadgesPage() {
    const { values, getPropItems } = usePropControls({
        children: {
            type: 'text',
            defaultValue: "Approved",
            description: "배지 텍스트",
            componentType: 'ReactNode'
        },
        variant: {
            type: 'segmented',
            defaultValue: 'default',
            options: ["default", "secondary", "destructive", "outline", "success"],
            description: "배지의 시각적 스타일 변형",
            componentType: '"default" | "secondary" | "destructive" | "outline" | "success"'
        }
    });

    return (
        <>
            <header className={styles.pageHeader}>
                <h1>Badges</h1>
                <p>상태나 카테고리를 표시하는 작은 시각적 라벨 컴포넌트입니다.</p>
            </header>

            <div className={styles.storySection}>
                <Story title="Standard Library" description="Core badge variants for semantic labeling">
                    <div className={styles.buttonRow}>
                        <Badge variant={values.variant as "default" | "secondary" | "destructive" | "outline" | "success"}>
                            {values.children as string}
                        </Badge>
                        <Badge variant="secondary">Secondary Muted</Badge>
                        <Badge variant="outline">Ghost Outline</Badge>
                        <Badge variant="destructive">Urgent / Error</Badge>
                        <Badge variant="success">Confirmed / Active</Badge>
                    </div>
                </Story>

                <Story title="Real-world Scenarios" description="How badges are applied within the Banana Wedding context">
                    <div className={styles.showcaseGrid}>
                        <div className={styles.iconTextRow}>
                            <Badge variant="success">APPROVED</Badge>
                            <span className={styles.textSmall}>Invitation is live and public</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge>PENDING</Badge>
                            <span className={styles.textSmall}>Waiting for administrator review</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge variant="destructive">REJECTED</Badge>
                            <span className={styles.textSmall}>Needs modification for approval</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge variant="secondary">DRAFT</Badge>
                            <span className={styles.textSmall}>Unpublished work in progress</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge variant="outline">SYSTEM</Badge>
                            <span className={styles.textSmall}>Automatic tag generated by server</span>
                        </div>
                    </div>
                </Story>

                <DocSection
                    usage={`import { Badge } from "@/components/ui/Badge";\n\n<Badge variant="${values.variant}">${values.children}</Badge>`}
                    props={getPropItems()}
                />
            </div>
        </>
    );
}
