"use client";

import React from "react";
import styles from "../DesignSystem.module.scss";
import { Badge } from "@/components/ui/Badge";
import Story from "../Story";

export default function BadgesPage() {
    return (
        <>
            <header className={styles.pageHeader}>
                <h1>Badges</h1>
                <p>상태나 카테고리를 표시하는 작은 시각적 라벨 컴포넌트입니다.</p>
            </header>

            <div className={styles.storySection}>
                <Story title="Standard Library" description="Core badge variants for semantic labeling">
                    <div className={styles.buttonRow}>
                        <Badge>Primary Default</Badge>
                        <Badge variant="secondary">Secondary Muted</Badge>
                        <Badge variant="outline">Ghost Outline</Badge>
                        <Badge variant="destructive">Urgent / Error</Badge>
                        <Badge variant="success">Confirmed / Active</Badge>
                    </div>
                </Story>

                <Story title="Real-world Scenarios" description="How badges are applied within the Banana Wedding context">
                    <div className={styles.showcaseGrid}>
                        <div className={styles.iconTextRow}>
                            <Badge variant="success">APPROVED</Badge>
                            <span className={styles.textSmall}>Invitation is live and public</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge>PENDING</Badge>
                            <span className={styles.textSmall}>Waiting for administrator review</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge variant="destructive">REJECTED</Badge>
                            <span className={styles.textSmall}>Needs modification for approval</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge variant="secondary">DRAFT</Badge>
                            <span className={styles.textSmall}>Unpublished work in progress</span>
                        </div>
                        <div className={styles.iconTextRow}>
                            <Badge variant="outline">SYSTEM</Badge>
                            <span className={styles.textSmall}>Automatic tag generated by server</span>
                        </div>
                    </div>
                </Story>

                <Story title="Code reference" description="Import and prop definitions">
                    <div className={styles.codePanel}>
                        <pre className={styles.monoText}>
                            {`import { Badge } from "@/components/ui/Badge";

<Badge variant="success">Approved</Badge>
<Badge variant="destructive">Error</Badge>`}
                        </pre>
                    </div>
                </Story>
            </div>
        </>
    );
}
